feat: populate readme with basic auth info
thingweb/node-red-contrib-web-of-things pull request #20
Opened 2021-03-18 17:39 UTC by fatadel

2021-03-18 17:44 UTC, sebastiankb requested changes

2021-03-18 17:44 UTC, sebastiankb commented on README.md
> +**Note:** Only basic type of authentication is currently supported.
... supported in this node-red contrib.

2021-03-18 17:50 UTC, fatadel commented on README.md
> +**Note:** Only basic type of authentication is currently supported.
Better now?

2021-03-19 06:43 UTC, sebastiankb commented
thanks

2021-03-19 06:44 UTC, sebastiankb approved these changes

2021-03-19 06:44 UTC, merged