develop serverside nodes
thingweb/node-red-contrib-web-of-things pull request #26
Opened 2024-02-06 13:51 UTC by hidetak

This is an implementation of the server-side node described in the following Issue.
https://github.com/thingweb/node-red-contrib-web-of-things/issues/25

The following modifications are also implemented for the client side.
* read property node execution is now triggered by input
* Wait until the observe property and subscribe event execution succeeds

2024-02-16 10:51 UTC, egekorkan commented
We discussed this in the call and @egekorkan will try using them in his computer. Then we can merge it and then move to the Eclipse Thingweb

2024-02-16 14:01 UTC, danielpeintner commented
> * modified to use node-wot 0.8.10

Minor: there is already node-wot v0.8.12 out. Updating to it shouldn't cause any issue since there are no API changes or such. Thanks!

2024-02-16 15:02 UTC, egekorkan requested changes
Small changes but overall, it is working. I just didn't manage to get the property on the server side working. I have just put the following in the function attached to the property:

![image](https://github.com/thingweb/node-red-contrib-web-of-things/assets/20195407/a7d4b3c4-8853-4246-b897-1ac0964e620d)

@hidetak how can I make it work? I get an empty payload when I read the property.

Overall, thank you many times for doing this work! You even have Japanese UI elements that will make Thingweb project international ;)

2024-02-16 15:02 UTC, egekorkan commented on package.json
> +    "url": "https://github.com/hidetak/node-red-contrib-web-of-things"
Could you keep these as is?

2024-02-16 15:02 UTC, egekorkan commented on package.json
> +  "homepage": "https://github.com/hidetak/node-red-contrib-web-of-things/blob/master/README.md",
Could you keep these as is?

2024-02-16 17:50 UTC, hidetak commented
@danielpeintner 

Thank you for your comment.
I have changed the version of node-wot to 0.8.12.

2024-02-16 17:52 UTC, hidetak commented on package.json
> +    "url": "https://github.com/hidetak/node-red-contrib-web-of-things"
Sorry, I forgot to correct the URL.
I have corrected it.

2024-02-16 17:52 UTC, hidetak commented on package.json
> +  "homepage": "https://github.com/hidetak/node-red-contrib-web-of-things/blob/master/README.md",
Sorry, I forgot to correct the URL.
I have corrected it.

2024-02-16 18:16 UTC, hidetak commented
@egekorkan 

Thank you for your confirmation.

<img width="997" alt="image" src="https://github.com/thingweb/node-red-contrib-web-of-things/assets/39742000/4b6ad483-d86b-413f-9f4f-1db6a071f8e8">

The input of a Server-Property node is done when there is a change to that property on the server side. At this time, it is not necessary to input the changed value.

The value returned to the client must be obtained by a flow connected to the first output of the Server-Property node and input to the Server-End node.

The value of the write is output from the second output of the Server-Property node, so the connected flow should process that value and the end should connect the Server-End node.

If you have any other questions, please feel free to ask.

> Overall, thank you many times for doing this work! You even have Japanese UI elements that will make Thingweb project international ;)

I am glad to hear you say so.
I hope to take the next step to internationalize the client side as well.
If there are any odd English words, I would appreciate it if you could point them out to me.

2024-02-16 21:41 UTC, egekorkan commented
@hidetak I have done the same thing once again and it worked, so I am sorry for the first comment about readproperty. I will now check the english and make commits if I see issues. If not, we can merge it and move to its new place

2024-02-16 21:54 UTC, egekorkan commented
I made some small changes and it is looking good. Merging.

When moving to Eclipse, I will try to follow https://www.johno.com/move-directory-between-repos-with-git-history so that the contributors are credited correctly. I hope it works otherwise it would look as if I did all the work.

2024-02-17 07:00 UTC, hidetak commented
@egekorkan 
> I made some small changes and it is looking good. Merging.

Thank you for the correction and merge.

2024-02-17 12:37 UTC, merged

2024-02-17 15:25 UTC, egekorkan commented
In the end, I have used the instructions at https://gist.github.com/trongthanh/2779392